services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=loan-application'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
